### ISSUE TITLE
Fluence artifact / bug when using gaussian source type

### ISSUE THREAD

**Issue by bernhardkaplan** [fangq/mcx#17]
when using a homogeneous block absorber (without scattering) with a gaussian-type light source, the fluence distribution shows two artifacts:
- concentric circles are visible
- the voxels in the center (along the beam axis) have lower fluence (see attached figure)
![gaussian_fluence_artifact](https://cloud.githubusercontent.com/assets/1629580/12421227/6f1f10c2-bec1-11e5-912c-995083825b45.png)

**Comment by fangq** [comment]
@bernhardkaplan

are you using the latest (from git) mcx code or a previous release? last year, I fixed a bug related to forward-scattering due to floating point round-off tests, see

https://github.com/fangq/mcx/commit/cd8f1348b138a7a5305c8e2215d433c2b04b9b71

if you are using an older release, it would be great if you can try the git version and let me know if this issue still presents.

by the way, what visualization software did you use for the 3D renderings? they look great!

**Comment by bernhardkaplan** [comment]
@fangq 
I'm using the latest version (SHA1 103ab04275833c50d5ac78be2f46dc402efbd781) from 2015-11-11, so the behavior is still present. 
For visualization I use Amira (for hand-guided inspection): http://www.fei.com/software/amira-3d-for-life-sciences/ 
but I plan to use Python for automated analysis scripts.

**Comment by fangq** [comment]
can you provide your input file and full command line? also the domain settings. 
I will look into this.

**Comment by bernhardkaplan** [comment]
The mcx command is:
time mcx -A --gategroup 1 --input parameterfile.json -s mcx_output_F1_nphotons5.0e+07_nx100_ny100_nz100_cnt0 --array 0 --reflect 1 --reflectin 0 --normalize 1 --skipradius -2 --outputtype F --seed 0 -H 50000000 --repeat 1 -G 1

the parameter file is here:
https://www.dropbox.com/s/jv4pdd973qsprwf/parameterfile.json?dl=0

and the volume file here:
https://www.dropbox.com/s/v3zuqami2pqcv0z/phantom_volume_F1_nphotons1.0e%2B07_nx100_ny100_nz100_cnt0.raw?dl=0

The parameterfile includes some entries that MCX does not require (but my Python framework around it). I hope that's all you need to reproduce the fluence artifacts - let me know otherwise! 

Thanks for looking into this!

**Comment by fangq** [comment]
@bernhardkaplan, I recently made some significant updates to MCX. One of the updates is to include two new RNGs - POSIX erand48 (period: 2^48-1) and xorshift128+ (2^128-1). 

https://github.com/fangq/mcx/commit/b14ccf157810e9f13c129c7a822d30ed6b570f79

If you compile mcx with "make", it will now use xorshift128+ RNG as the default. 

can you update your software and rerun your test? 

Be aware, if you compile MCX with CUDA 7.5 and run the simulation on a Maxwell GPU (9xx), you will get 10x slow-down because of a CUDA bug. We have reported this bug to NVIDIA and it will be fixed with the next driver update. To get MCX work at full speed with a Maxwell GPU, you need to use CUDA 7.0 or CUDA 6.5. Please see this discussion for details

https://devtalk.nvidia.com/default/topic/925630/cuda-programming-and-performance/cuda-7-5-on-maxwell-980ti-drops-performance-by-10x-versus-cuda-7-0-and-6-5/1

Please let me know if this pattern remains when using the new RNG.

**Comment by bernhardkaplan** [comment]
The updated code has fixed the buggy source pattern - thanks for the fix!
![mcx_source_comparison](https://cloud.githubusercontent.com/assets/1629580/14422753/9a95c20c-ffd8-11e5-8822-6600cb7c9cd6.png)

**Comment by fangq** [comment]
terrific. I am closing this issue for now.

still, we need to figure out what's wrong with the LL5 RNG.

**Comment by fangq** [comment]
@bernhardkaplan, can you recompile mcx with "make fermi" and rerun your tests? 

just want to see if the artifact was caused by the RNG or by the ray-tracer algorithm. thanks

**Comment by bernhardkaplan** [comment]
when compiled with "make fermi" the buggy pattern reappears

**Comment by fangq** [comment]
I see. this seems to pinpoint to the old RNG. I have a student who is doing some rigorous RNG tests. will update.

**Comment by fangq** [comment]
this bug seems to be related to Issues #31, #29 and #26; it is particularly similar to #26.

my guess was that 3 these issues were caused by the same problem that was fixed in #31. The varied shapes of the artifact was a result of the low-quality host (CPU) RNG on Windows on different RNGs:

the hollow center and a line artifact like in #17 and #26 seems to be the logistic-lattice RNG influenced by poor initial RNG states on Windows.

the 4-dot structures like in #31 and #29 are the result of the xorshift128+ RNG influenced by the same bug on Windows.

as a result, this bug actually impacts all previous releases of mcx/mcxlab on windows. When running large photon numbers, the influence of the initial RNG states seems to get smoothed, there is still a bias in the solution that should have been fixed. I apologize for capturing this only now.
